Update github-actions.yml

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -22,45 +22,48 @@ jobs:
         uses: actions/checkout@v4
       - uses: hashicorp/setup-terraform@v3
       
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'adopt'  # Specify the JDK distribution
-          java-version: '11'
+      # - name: Set up JDK 11
+      #   uses: actions/setup-java@v2
+      #   with:
+      #     distribution: 'adopt'  # Specify the JDK distribution
+      #     java-version: '11'
 
-      - name: Install .NET SDK
-        uses: actions/setup-dotnet@v2
-        with:
-          dotnet-version: '6.0.x'
+      # - name: Install .NET SDK
+      #   uses: actions/setup-dotnet@v2
+      #   with:
+      #     dotnet-version: '6.0.x'
 
 
-      #  Step to install OWASP dependency check and run it
-      - name: Install OWASP Dependency-Check
-        run: |
-          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.1/dependency-check-6.5.1-release.zip
-          unzip dependency-check-6.5.1-release.zip
-          sudo mv dependency-check /usr/local/bin/dependency-check
+      # #  Step to install OWASP dependency check and run it
+      # - name: Install OWASP Dependency-Check
+      #   run: |
+      #     wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.1/dependency-check-6.5.1-release.zip
+      #     unzip dependency-check-6.5.1-release.zip
+      #     sudo mv dependency-check /usr/local/bin/dependency-check
 
-      - name: Run OWASP Dependency-Check
-        run: |
-          /usr/local/bin/dependency-check/bin/dependency-check.sh --project "myproject" --scan . --format "ALL" --disableAssembly
+      # - name: Run OWASP Dependency-Check
+      #   run: |
+      #     /usr/local/bin/dependency-check/bin/dependency-check.sh --project "myproject" --scan . --format "ALL" --disableAssembly
 
-      - name: Check for vulnerabilities
-        run: |
-          if grep -q "CRITICAL" dependency-check-report.html; then
-            echo "Critical vulnerabilities found!"
-            exit 1
-          else
-            echo "No critical vulnerabilities found."
-          fi
+      # - name: Check for vulnerabilities
+      #   run: |
+      #     if grep -q "CRITICAL" dependency-check-report.html; then
+      #       echo "Critical vulnerabilities found!"
+      #       exit 1
+      #     else
+      #       echo "No critical vulnerabilities found."
+      #     fi
 
-      - name: Upload Dependency-Check Report
-        if: failure()  # Upload report if there is a failure
-        uses: actions/upload-artifact@v2
-        with:
-          name: dependency-check-report
-          path: dependency-check-report.html
-          
+      # - name: Upload Dependency-Check Report
+      #   if: failure()  # Upload report if there is a failure
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: dependency-check-report
+      #     path: dependency-check-report.html
+
+      - name: Test for vulnerabilities
+        run: snyk test --severity-threshold=high    
+        
       # Step to determine the current version
       - name: Read current version
         id: current_version
